import { AppConfig, TaskItem } from '../types';

export function generateBloggerStandaloneHtml(config: AppConfig, tasks: TaskItem[]): string {
  const tasksJson = JSON.stringify(tasks.filter(t => t.active), null, 2);
  const configJson = JSON.stringify(config, null, 2);

  return `<!doctype html>
<html lang="bn" class="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover">
<title>${config.siteName} — ${config.tagline}</title>

<!-- Telegram WebApp SDK -->
<script src="https://telegram.org/js/telegram-web-app.js"></script>

<!-- Firebase Compat SDK -->
<script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js"></script>
<script src="https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore-compat.js"></script>

<!-- Monetag Official SDK Only (AdsGram Removed) -->
<script src="//libtl.com/sdk.js" data-zone="${config.monetagZoneId}" data-sdk="${config.monetagSdkFunc}"></script>

<link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@400;500;600;700&family=Syne:wght@700;800&display=swap" rel="stylesheet">

<style>
:root {
  --bg: #0c0714;
  --card: rgba(29, 18, 46, 0.82);
  --line: rgba(245, 158, 11, 0.22);
  --text: #fdf8f5;
  --muted: #b5a3c9;
  --gold: #f59e0b;
  --gold2: #fbbf24;
  --rose: #e11d48;
  --violet: #a855f7;
}
body.light-mode {
  --bg: #fcf9f6;
  --card: rgba(255, 255, 255, 0.92);
  --line: rgba(217, 119, 6, 0.24);
  --text: #1c1026;
  --muted: #6e5980;
}
* { box-sizing: border-box; margin: 0; padding: 0; -webkit-tap-highlight-color: transparent; }
body { background: var(--bg); color: var(--text); font-family: 'Hind Siliguri', sans-serif; min-height: 100vh; padding-bottom: 92px; transition: background 0.3s, color 0.3s; }
.app { max-width: 480px; margin: 0 auto; padding: 14px; }
.glass { background: var(--card); backdrop-filter: blur(18px); border: 1px solid var(--line); border-radius: 22px; padding: 18px; margin-bottom: 14px; position: relative; overflow: hidden; }
.btn-gold { width: 100%; padding: 14px; border-radius: 14px; border: 0; font-weight: 700; cursor: pointer; background: linear-gradient(135deg, var(--gold), var(--rose)); color: #fff; font-size: 15px; }
</style>
</head>
<body>
<!-- Generated by ${config.siteName} Admin Studio -->
<script>
const APP_CONFIG = ${configJson};
const ACTIVE_TASKS = ${tasksJson};
// Monetag Ad Function: window[APP_CONFIG.monetagSdkFunc]()
// Real Telegram Channel Verification via Bot API getChatMember:
async function verifyTelegramMembership(channelUsername, userId) {
  if (!APP_CONFIG.telegramBotToken || !channelUsername) return false;
  const res = await fetch(\`https://api.telegram.org/bot\${APP_CONFIG.telegramBotToken}/getChatMember?chat_id=\${encodeURIComponent(channelUsername)}&user_id=\${userId}\`);
  const data = await res.json();
  return data.ok && ['member', 'administrator', 'creator'].includes(data.result?.status);
}
</script>
</body>
</html>`;
}
